[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
".gitignore_global" = "~/.gitignore"
".zshrc" = "~/.zshrc"
".tool-versions" = "~/.tool-versions"

".config/bat" = { target = "~/.config/bat", type = "symbolic" }
".config/gh" = { target = "~/.config/gh", type = "symbolic" }
".config/ghostty" = { target = "~/.config/ghostty", type = "symbolic" }
".config/nvim" = { target = "~/.config/nvim", type = "symbolic" }
".config/omp.json" = { target = "~/.config/omp.json", type = "symbolic" }
".config/fastfetch" = { target = "~/.config/fastfetch", type = "symbolic" }

".claude/CLAUDE.md" = "~/AGENTS.md"
".claude/settings.json" = "~/.claude/settings.json"
".claude/statusline.sh" = "~/.claude/statusline.sh"

"aliases.zsh" = "~/.oh-my-zsh/custom/aliases.zsh"

[default.variables]

[macos]
depends = ["default"]

[macos.files]
"cursor/settings.json" = "~/Library/Application Support/Cursor/User/settings.json"
"cursor/keybindings.json" = "~/Library/Application Support/Cursor/User/keybindings.json"
".colima/colima.yaml" = "~/.colima/default/colima.yaml"
".docker/config.json" = "~/.docker/config.json"

[linux]
depends = ["default"]

[linux.files]
"cursor/settings.json" = "~/.config/Cursor/User/settings.json"
"cursor/keybindings.json" = "~/.config/Cursor/User/keybindings.json"
".docker/config.linux.json" = { target = "~/.docker/config.json", type = "template" }

[settings]
default_target_type = "automatic"
