[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
".gitignore_global" = "~/.gitignore"
".zshrc" = "~/.zshrc"
".config" = { target = "~/.config", type = "symbolic" }
".tool-versions" = "~/.tool-versions"

".claude/settings.json" = "~/.claude/settings.json"
".claude/statusline.sh" = "~/.claude/statusline.sh"

"aliases.zsh" = "~/.oh-my-zsh/custom/aliases.zsh"

[default.variables]

[macos]
depends = ["default"]

[macos.files]
"cursor/settings.json" = "~/Library/Application Support/Cursor/User/settings.json"
"cursor/keybindings.json" = "~/Library/Application Support/Cursor/User/keybindings.json"

[linux]
depends = ["default"]

[linux.files]
"cursor/settings.json" = "~/.config/Cursor/User/settings.json"
"cursor/keybindings.json" = "~/.config/Cursor/User/keybindings.json"

[settings]
default_target_type = "automatic"
