[helpers]

[default]
depends = []

[default.files]
".gitconfig" = "~/.gitconfig"
".gitignore_global" = "~/.gitignore"
".zshrc" = "~/.zshrc"
".config" = { target = "~/.config", type = "symbolic" }
".tool-versions" = "~/.tool-versions"

".claude/settings.json" = "~/.claude/settings.json"
".claude/statusline.sh" = "~/.claude/statusline.sh"

"aliases.zsh" = "~/.oh-my-zsh/custom/aliases.zsh"

[default.variables]

[settings]
default_target_type = "automatic"
